#pragma once

#define MODEL_SCALE 0.0039216
#define MODEL_CLASS_CNT 1
#define MODEL_MEAN 0.0
#define MODEL_THRESH 0.4
#define MODEL_NMS_THRESH 0.6
#define VIDEO_RECORD_FRAME_WIDTH 256
#define VIDEO_RECORD_FRAME_HEIGHT 256